source 'https://rubygems.org'
gem 'rails', '4.0.0'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer', :platforms => :ruby
gem 'uglifier', '>= 2.1.2'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'mysql2'
gem 'protected_attributes'
gem 'zurb-foundation'
gem 'jquery-datatables-rails'
gem 'chosen-rails'
gem 'compass-rails', github: "Compass/compass-rails", branch: "rails4-hack"
# gem 'compass-rails', github: 'milgner/compass-rails', branch: 'rails4'
gem 'tinymce-rails'
gem 'nokogiri', :require => "nokogiri"
gem 'roo'
